### ISSUE TITLE
[2.3] Extras Compatibility

### ISSUE THREAD

**Issue by exside** [modxcms/revolution#11630]
I think it would be good to collect working and more important not-yet-working extras in one place (maybe for the release note?) as more and more are reported. 

As far as I can tell, most not-working extras are affected by the connector nuking that happened in 2.3, so they don't find the appropriate processors anymore and thus do not work anymore. Another quite commonly observed issue is the use of the depreciated $modx->getMicrotime() method in extras. Just replacing it with PHP's native function microtime(true) fixes this problem.

I suggest commenting (including version info) about successfully and not successfully tested extras in this issue and a I will update the following list.

**Extras working and compatible with 2.3**
- [x] Ace 1.5.0-pl (@pixelchutes)
- [x] ActivationEmail 1.1.2-pl (@BobRay)
- [x] AjaxForm-1.0.2-pl (@absent42)
- [x] AjaxManager 1.1.8-pl (@whitebyte)
- [x] AjaxUpload 1.1.0-pl (@absent42)
- [x] Archivist 1.2.4-pl (@absent42)
- [x] Babel 2.2.5-pl (@DESIGNfromWITHIN, @goldsky 3.0.0-beta is available for testing)
- [x] BannerY 1.3.0-rc1 (@bezumkin)
- [x] Batcher 1.1.1-pl (@sottwell)
- [x] BigBrother 1.1.0-rc2 (@beau-gosse, doesn't work with PHP 5.4+ though, @exside)
- [x] BotBlockX 1.0.2-pl (@BobRay)
- [x] BreadCrumb 1.4.2-pl (@rdegler)
- [x] Breadcrumbs 1.1.0-pl (@sepiariver)
- [x] CacheClear 1.0.3-pl (@exside, @BobRay)
- [x] CacheMaster 1.2.1-pl (@BobRay)
- [x] Canonical 1.0-Beta1 (@BobRay)
- [x] Captcha 3.3.2-pl (@BobRay)
- [x] CaseInsensitiveURLs 1.2.0-pl1 (@BobRay)
- [x] CheckboxSortable 0.3.0-beta3 (@sottwell)
- [x] ClassExtender 2.0.0-pl (@sottwell, @BobRay)
- [x] Cliche 1.1.0-rc1 (@bentejuy, has some visual glitches)
- [x] ClientConfig 1.3.1-pl (@sottwell, @amdbuilder)
- [x] Collections 2.0.0-pl (@theboxer)
- [x] ColorPicker 1.0.2-rc2 (@atripolskyy, @pyrographics, @exside)
- [x] Console 2.0.1-beta (@exside)
- [x] ConvertDatabaseCharset (@BobRay, not a package, see http://bobsguides.com/convert-db-utf8.html)
- [x] cookieJar 1.0.0-pl (@davidpede)
- [x] Copyright 1.0-pl (@amdbuilder)
- [x] CSS Star Rating 2.0-rc1 (@pixelchutes)
- [x] cssSweet 1.1.0-rc1 (@sottwell)
- [x] CustomUrls 1.0.0-rc3 (@Boddlnagg)
- [x] DBAPI 1.0.2-pl, pending release. (@pixelchutes)
- [x] DefaultResourceGroup 1.1.0-pl (@BobRay)
- [x] DefaultUserGroup 1.1.0-pl (@BobRay)
- [x] Dirwalker 1.0.0-pl (@BobRay)
- [x] EmailResource 1.1.3 (@BobRay)
- [x] EmptyAlias 1.0.0-beta1 (@BobRay)
- [x] EZfaq 3.3.0-pl (@BobRay)
- [x] fastField 1.4.0-pl (@mintnl)
- [x] FileDownload R 1.1.7-pl (@absent42)
- [x] FileLister 1.1.1-pl (@mintnl, however keep in mind to use a relative path, so paths starting with /)
- [x] FileUpload 1.0.4-pl (@BobRay)
- [x] firstPageLink 1.0.1-pl (@Boddlnagg)
- [x] FixedPre 1.2.2-pl (@BobRay)
- [x] FormIt 2.2.0-pl (@pixelchutes)
- [x] Gallery 1.7.0-pl (@pixelchutes)
- [x] Gateway Manager 1.1.2-pl (@amdbuilder)
- [x] getCache 1.1.0-pl (@sepiariver)
- [x] getDate 1.0.0-pl (@davidpede)
- [x] getPage 1.2.4-pl (@sepiariver)
- [x] getRelated 1.2.0-pl (@sepiariver)
- [x] getResourceField 1.0.3-pl1 (@mcnickel)
- [x] getResources 1.6.1-pl (@sepiariver)
- [x] getUrlParam 1.0-beta1 (@absent42)
- [x] getVimeo 1.1.0-pl (@davidpede)
- [x] getYoutube 1.0.0-pl (@davidpede)
- [x] GoogleAuthenticatorX 1.0.0-rc2 (@minagerges)
- [x] GoogleSiteMap 1.3.1-pl (@mcnickel)
- [x] Grid Class Key 1.0.1-beta1 (@goldsky, could break with compress_js on @labr1005)
- [x] HandyMan 1.0.0-pl (@absent42)
- [x] If 1.1.1-pl (@funkyduke)
- [x] JSONDerulo 2.4.0-pl (@pdincubus)
- [x] LikeDislike 1.0.3-rc1 (@amdbuilder,  Works with Display issues)
- [x] Login 1.8.1-pl (@pixelchutes)
- [x] LogLogins 1.1.0-pl (@BobRay)
- [x] LogPageNotFound 1.0.3-pl (@BobRay)
- [x] MandrillX 1.0.3-pl (@pyrographics, @BobRay)
- [x] MetaX 2.0.2-pl (@amdbuilder)
- [x] mhpaypal 1.1.1-rc1 (@absent42)
- [x] MIGX 2.8.1-pl, has a lot of styling / UI issues though (@exside), MIGX AJAX Upload (http://rtfm.modx.com/extras/revo/migx/migx.tutorials/migx.use-resource-specific-mediasource-and-multifile-uploader) seems not to work (@skazhikadyadya)
- [x] MinifyX 1.3.1-pl (@amdbuilder)
- [x] miniShop2 2.1.8-rc2 (@bezumkin)
- [x] modAvatar 1.1.0-beta (@absent42)
- [x] modMailchimp 1.0.6-pl (@absent42)
- [x] MODX Revolution Boilerplate 1.0.1-pl (@pdincubus)
- [x] MultiUploadDialog 1.0.2-pl (@absent42)
- [x] MyComponent 3.2.2-pl (@pixelchutes, @BobRay)
- [x] NewsPublisher 1.4.2-pl (@BobRay, issues with TinyMCE though, @sottwell)
- [x] Notify 1.2.3-pl (@BobRay)
- [x] ObfuscateEmail-Revo 1.0.0-pl (@absent42)
- [x] ObjectExplorer 1.1.2-pl (@BobRay)
- [x] Orphans 1.1.0-pl (@BobRay, @sottwell)
- [x] PageLocker 1.1.0-beta1 (@gleighfield)
- [x] paramStash 1.3.0-pl (@electrickite)
- [x] pdoTools 1.9.2-pl1 (@sottwell)
- [x] Personalize 3.7.0-pl (@wshawn, @BobRay)
- [x] PiwikVisitsSummary 1.0.4-pl (@lektriq)
- [x] Polls 1.3.2-pl (@exside, CMP works, Frontend untested)
- [x] Profiler 1.1.0-pl (@TheBoxer)
- [x] Provisioner 1.1.0-pl, confirmed for importing Evo sites *(did not test Revo import < 2.1.3)* (@pixelchutes)
- [x] QuickEmail 1.1.0-pl (@BobRay)
- [x] Quickstart Buttons 1.1.1-pl (@Mark-H, needs modmore account/package provider for download, see https://www.modmore.com/extras/quickstartbuttons/, css fix for 2.3.1 see here http://forums.modx.com/thread/92587/quickstart-buttons-addon---css-for-modx-2-3-1)
- [x] Quip 2.3.3-pl (@amdbuilder, @mintnl)
- [x] Redirector 2.0.5-pl (@beau-gosse, there may well be issues with this extra not related to 2.3 @juiceCake)
- [x] ReflectBlock 1.1.0-pl (@BobRay)
- [x] RefreshCache 1.1.0-pl (@BobRay)
- [x] ResourceExplorer 1.0.0-pl2 (@xgenvn, minor display glitches, fix coming soon)
- [x] SE Manager for MODX 0.2.0-pl (@Alroniks)
- [x] selfLink 1.0.0-pl (@mcnickel)
- [x] SEO Pro 1.0.3-pl (@christianseel)
- [x] SEO Tab 1.0.10-pl (@christianseel)
- [x] Shibboleth 0.4.0-pl (@electrickite)
- [x] Shopkeeper 2.3.7-pl (@zfjoury)
- [x] ShowTV 1.0.0-beta1 (@BobRay)
- [x] siblingNav 1.0.1-pl (@sottwell)
- [x] SimpleSearch 1.9.0-pl (@sepiariver)
- [x] SiteAtoZ 1.0.3-beta1 (@BobRay)
- [x] SiteCheck 1.0.2-pl (@BobRay, premium Extra https://gumroad.com/l/DLChJ)
- [x] sitemapFriend 1.0.2-pl1 (@mcnickel)
- [x] SPForm 3.2.2-pl (@BobRay)
- [x] StageCoach 1.4.0-pl (@BobRay)
- [x] Subscribe 1.2.1-pl (@BobRay)
- [x] SyntaxHighlighter 1.0.0-beta1 (@BobRay)
- [x] TableofContentsX 1.0.1-pl1 (@MacConin)
- [x] Tagger 1.5.0-pl (@TheBoxer)
- [x] tagManager2 2.0.0-rc4 (@zfjoury)
- [x] ThemePackagerComponent 1.3.0-dev1 (@sottwell confirmed working but non-2.3 related issues, @jeremysanchez reported problems in 2.3.1)
- [x] ThermX 3.1.0-pl1 (@BobRay)
- [x] TimerangeTV 1.1.0-pl (@exside, @leqtrik)
- [x] TrackDuck 1.1.1-pl1 (@shauchenka)
- [x] translit 1.0.0-beta (@zfjoury)
- [x] TwitterX 1.3.4-pl (@absent42)
- [x] UltimateParent 2.0.0-pl (@mcnickel)
- [x] UserUrls 0.1.3-beta (@wshawn)
- [x] VersionX 2.1.0-pl (@amdbuilder, minor issues https://github.com/Mark-H/VersionX2/issues/67)
- [x] Wayfinder 2.3.3-pl (@pixelchutes, @sepiariver)
- [x] xBug 0.7.5-pl (@the-dunnock)
- [x] XRouting 1.2.0-pl (@labr1005)

**Extras working in 2.3 but not showing up in package manager**
- [x] AutoTemplate 1.0.0-rc1 (@oblongd)
- [x] MarkitUp 0.0.5-pl (@darkarchon)
- [x] modxTalks 1.0.3-beta (@sottwell)
- [x] sanitizeupload 1.0.0-rc (@absent42)
- [x] Theme.Bootstrap 2.1.0-pl (@opus4711)
- [x] visualSitemap 1.0.1-beta2 (@wshawn)
- [x] xFPC 2.1.0-pl1 (@mcnickel, xFPCAjax not tested, according to @MacConin the plugin gives warnings but seems to work; @funkyduke; @Gallenkamp also reports massive error logging issues with a 2.3.2. installation; @absent42 reports these logging issues for 2.2.x installations too; @sottwell points out that the issues are most possibly coming from setting headers too late)

**Extras partially working in 2.3**
- [x] Articles 1.7.9-pl (@jpdevries, @Mark-H, @amdbuilder, @hitodev found that it's not possible to remove tags due to the missing "delete"/cross button, see http://forums.modx.com/thread/92526/articles-extra-tags-missing-delete-icon + probable issues together with Tagger 1.5.0-pl, View and close buttons do not seem to work properly)
- [x] CKEditor 1.1.1-pl https://github.com/danyaPostfactum/modx-ckeditor/issues/17 (@exside)
- [x] CodeMirror 2.2.1-pl (@pdincubus confirmed working in 2.3.1, @sottwell reported issue with longer files, see comment from @charlie17)
- [x] ContextRouter 1.1.0-pl2 (@wshawn, 2.3.1 should be fine, in 2.3.0 you need to add a return statement to the plugin)
- [x] CronManager 1.1.0-pl (@pyrographics)
- [x] FormSave 1.1.0-pl1 (@pixelchutes, @bradbertz When viewing formsave form submission list, scroll down the list seems not to work (see https://github.com/b03tz/FormSave/issues/27). Package not showing up in packager browser
- [x] Google Analytics Dashboard Widget 1.0.1-pl (@absent42, @leqtrik, layout is broken and package not showing in package browser, for fix see http://forums.modx.com/thread/92380/google-analytics-dashboard-widget-1-0-1-pl-layout-fix-for-modx-2-3-x or http://forums.modx.com/thread/92525/analytics-dashboard-widget---display-glitch-in-revo-2-3)
- [x] Image+ 2.2.0-pl (has quite some UI issues, not really production ready, @exside)
- [x] phpThumbOf 1.4.0-pl (affected by #11700, @le-genda)
- [x] phpThumbsOn 1.2.1-pl (affected by #11700, @le-genda)
- [x] pThumb 2.3.3-pl (@exside, affected by #11700 @le-genda, issue as an output filter, scaling params are ignored when using Resizer @juiceCake)
- [x] SuperBoxSelect 1.0.1-pl2 (@enigmatic-user, @exside, UI issues due to additional styles for the already existing superboxselect styles in the core + missing classes for the triggers and tags, see fix in comments below, also not showing in package browser)
- [x] TinyMCE 4.3.3-pl, working but some paths need updating, seems non-breaking atm though, maybe some issues with fullscreen-mode (@sepiariver, @sottwell, @linlex, @rainbowtiger)

**Extras not working with 2.3**
- [x] AdvSearch 1.0.1-pl (@sottwell, @whitebyte error because of depreciated/removed getMicroTime() in 2.3, for a fix see #11749)
- [x] ElementHelper 1.3.3-pl (https://github.com/roryg/ElementHelper/issues/26, main issue also the use of deprecated $modx->getMicrotime(), but it's also not showing up in package manager)
- [x] Formz 1.1.0-pl (@markwillis82 reported it's working but according to http://forums.modx.com/thread/92765/formz-error-on-revolution-2-3-1#dis-post-506876 saving new forms doesn't work, which renders the extra useless)
- [x] Group Edit 1.2.0-pl (@Systerr; Autor recommends using Collections as repalcement)
- [x] ImportX 1.1.1-pl (@jmbuytaert reports that it only imports 2 entries)
- [x] Janitor 1.6-beta Search tab (port of Evo DocFinder) does not work: `Could not find action file at: controllers/default/index.php`, referencing legacy 2.2 action IDs for updating resources / elements, etc. e.g. `/manager/index.php?a=30&id=16`
- [x] mxCalendar 1.1.10-pl (@amdbuilder)
- [x] mxFormBuilder 1.0.0-pl (not showing up in package browser and CMP not working according to http://forums.modx.com/thread/92724/mxformbuilder-window-opens-briefly-then-blank#dis-post-506653)
- [x] MODXRated 2.1.0-pl (@hugopeek)
- [x] PackMan 1.2.0-pl (@exside, CMP works but has some minor UI issues, functionality has issues according to @pdincubus, @minagerges)
- [x] revoSSL 1.0.3-pl (@pyrographics)
- [x] Xodus 1.4.0-beta (@andreborud, It seems to generate the csv or xls but upon download it just jumps back to the dashboard, package not showing in package browser)

**Extras that need testing / confirmation (list incomplete)**
- [ ] charcounterTV 1.1.0-pl (not showing up in package browser)
- [ ] ColorPicker 1.0-beta1 (not showing in package browser)
- [ ] Databackup 1.1.9-pl (not showing in package browser)
- [ ] DirectResize 1.3.1-rc1
- [ ] Discuss 1.2-pl
- [ ] GoogleMapsTV 1.0-rc3
- [ ] mChimpX 1.0.0-rc1
- [ ] modActiveDirectory 1.0.1-pl
- [ ] modxRepository 1.2.3-beta

**Comment by leoandrews** [comment]
Does anyone know if any of these work in 2.3?

firstchildredirect 2.3.1-pl
getFeed 1.0.0-pl
phpThumbOf 1.4.0
PHPThumbFilter 0.6.1-rc2
Redirector 1.0.3-pl (newer versions don't work with revo 2.2x)
TinyMCE 4.4.0-pl
Uncacher 0.1.0-pl

**Comment by enminc** [comment]
pThumb works.... you should not use phpThumbOf anymore....

**Comment by MacConin** [comment]
firstchildredirect 2.3.1-pl works
also Tinymce

**Comment by Gallenkamp** [comment]
Did anyone try SlideshowManager yet?
http://modx.com/extras/package/slideshowmanager

**Comment by funkyduke** [comment]
@Gallenkamp don't use slideshowmanager, create your own slideshow with Migx, much better to control

**Comment by Gallenkamp** [comment]
SlideshowManager is exactly what clients expect (and so do I). And it is working within 2 minutes.
If we want MODX to become a nerd CMF, ok. But that is not my choice to make. I serve my clients and they need it fast and simple :)

**Comment by Nuan8** [comment]
Discuss 1.2-pl works with 2.3

**Comment by Halfnium** [comment]
Am currently using sekFancyBox version 1.03-pl (latest according to Package Manager) with Revo 2.2.14-pl.  Looking to upgrade to Revo 2.3.3.  Any known issues before I take an upgrade step that might be difficult to reverse?

Noting that it sekFancyBox compatibility was not listed in the original July 4, 2014 posting here, and that this Extra's documentation has not been updated since December 8, 2012, I'm open to suggestions with regard to replacing it.

Thanks!

**Comment by jgulledge19** [comment]
Databackup 1.1.9-pl works on 2.3 and should now show up in package management. Thanks!

**Comment by elz64** [comment]
After sending an issue to Rico https://github.com/mikrobi/babel
Babel 3.0 beta3 is mandatory for BabelTranslation snippet to work again once Revo is updated to 2.33 (no issue upto 2.32, but once upgraded to 2.33 all Babeltranslation links vanished). Rico did it fast.

**Comment by pyrographics** [comment]
ModMobile or Mobile Detection compatible? Neither display in package manager.

**Comment by RobertSK** [comment]
As far as I remember Mobile Detection works, but you have to make 2-3 changes to the snippet first.
It uses a not longer supportet log function, so you need to comment out or replace that, see MODX Error Log.
I will look into what I did and give more information later today or tomorrow

**Comment by pyrographics** [comment]
Thanks RobertSK, I'm trying modMobile and it seems to have issues.

**Comment by sebastian-marinescu** [comment]
imageSlim 1.1.3-pl (new install) is working on 2.3.3

**Comment by Mark-H** [comment]
I'm going to close this issue as 2.3 has been out for a while now and there are only few extras that have remaining issues. In those cases contacting the author on the github pages is the best way to move forward. 

Packages not showing up in the 2.3 package manager can also be resolved by the author of that extra by changing the compatibility status of the package.
